"""Crear esquema inicial

Revision ID: 1d1637a164b2
Revises: 
Create Date: 2026-09-14 16:14:40.524725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1637a164b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nivel_ingles',
    sa.Column('id_nivel_ingles', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_nivel_ingles'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_emisor',
    sa.Column('id_tipo_emisor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_emisor'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo_error',
    sa.Column('id_tipo_error', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_error'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nombre_visible', sa.String(length=100), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('configuracion_usuario',
    sa.Column('id_configuracion_usuario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('velocidad_habla', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('paciencia_segundos', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ocultar_transcripcion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_configuracion_usuario'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('tema',
    sa.Column('id_tema', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_nivel_ingles', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('prompt_base', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_nivel_ingles'], ['nivel_ingles.id_nivel_ingles'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tema'),
    sa.UniqueConstraint('id_usuario', 'nombre', name='uq_tema_usuario_nombre')
    )
    op.create_table('usuario_proveedor_auth',
    sa.Column('id_usuario_proveedor_auth', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=30), nullable=False),
    sa.Column('id_externo_proveedor', sa.String(length=255), nullable=False),
    sa.Column('fecha_vinculacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_proveedor_auth'),
    sa.UniqueConstraint('proveedor', 'id_externo_proveedor', name='uq_proveedor_idexterno')
    )
    op.create_table('vocabulario',
    sa.Column('id_vocabulario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('palabra_o_frase', sa.String(length=200), nullable=False),
    sa.Column('significado', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_vocabulario'),
    sa.UniqueConstraint('id_usuario', 'palabra_o_frase', name='uq_vocabulario_usuario_palabra')
    )
    op.create_table('sesion',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_tema', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('puntaje_promedio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_tema'], ['tema.id_tema'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_table('mensaje',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_tipo_emisor', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_tipo_emisor'], ['tipo_emisor.id_tipo_emisor'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('correccion',
    sa.Column('id_correccion', sa.Integer(), nullable=False),
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_tipo_error', sa.Integer(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('texto_corregido', sa.Text(), nullable=False),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensaje.id_mensaje'], ),
    sa.ForeignKeyConstraint(['id_tipo_error'], ['tipo_error.id_tipo_error'], ),
    sa.PrimaryKeyConstraint('id_correccion')
    )
    op.create_table('vocabulario_ocurrencia',
    sa.Column('id_vocabulario_ocurrencia', sa.Integer(), nullable=False),
    sa.Column('id_vocabulario', sa.Integer(), nullable=False),
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('fecha_ocurrencia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensaje.id_mensaje'], ),
    sa.ForeignKeyConstraint(['id_vocabulario'], ['vocabulario.id_vocabulario'], ),
    sa.PrimaryKeyConstraint('id_vocabulario_ocurrencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulario_ocurrencia')
    op.drop_table('correccion')
    op.drop_table('mensaje')
    op.drop_table('sesion')
    op.drop_table('vocabulario')
    op.drop_table('usuario_proveedor_auth')
    op.drop_table('tema')
    op.drop_table('configuracion_usuario')
    op.drop_table('usuario')
    op.drop_table('tipo_error')
    op.drop_table('tipo_emisor')
    op.drop_table('nivel_ingles')
    # ### end Alembic commands ###
